# Python科学计算库Numpy

确保第一个事，咱们要用的库已经安装好了

In [2]:
import numpy as np

In [2]:
array = [1,2,3,4,5]
array + 1

TypeError: can only concatenate list (not "int") to list

In [4]:
array = np.array([1,2,3,4,5])
print(type(array))

<class 'numpy.ndarray'>


In [11]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [12]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [13]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [14]:
array[0]

1

In [15]:
array[3]

4

In [16]:
array

array([1, 2, 3, 4, 5])

In [17]:
array.shape

(5,)

In [18]:
tang_list = [1,2,3,4,5]
tang_list.shape

AttributeError: 'list' object has no attribute 'shape'

In [19]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)