In [1]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换

In [2]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

ndarray基本属性操作

In [3]:
type(tang_array) # 查看类型

numpy.ndarray

In [4]:
tang_array.dtype #查看数组的数据类型

dtype('int32')

In [5]:
tang_array.itemsize # 查看数组中每个元素的字节大小

4

In [6]:
tang_array.shape # 查看数组的形状

(5,)

In [7]:
tang_array.size # 查看数组的元素个数

5

In [8]:
np.size(tang_array) # 查看数组的元素个数

5

In [9]:
np.shape(tang_array) # 查看数组的形状

(5,)

In [10]:
tang_array.ndim # 查看数组的维度

1

In [11]:
tang_array # 查看数组的内容

array([1, 2, 3, 4, 5])

In [12]:
tang_array.fill(0) # 将数组中的元素全部填充为0
tang_array

array([0, 0, 0, 0, 0])

索引与切片:跟Python都是一样的 还是从0开始的

In [13]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

1

In [14]:
tang_array[1:3]

array([2, 3])

In [15]:
tang_array[-2:]

array([4, 5])

矩阵格式（多维的形式）

In [16]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
tang_array.shape

(3, 3)

In [18]:
tang_array.size

9

In [19]:
tang_array.ndim

2

In [20]:
tang_array[1,1]

5

In [21]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [22]:
tang_array[1]

array([ 4, 10,  6])

In [23]:
tang_array[:,1]

array([ 2, 10,  8])

In [24]:
tang_array[0,0:2]

array([1, 2])

In [25]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [26]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [27]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [28]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [29]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [30]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [31]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [32]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
mask = np.array([0,0,0,1,1,1,0,0,1,1],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [34]:
tang_array[mask]

array([30, 40, 50, 80, 90])

In [35]:
random_array = np.random.rand(10) # 生成一个包含10个随机数的数组,范围是
random_array

array([0.87552676, 0.75721475, 0.413712  , 0.66101411, 0.56544024,
       0.33231357, 0.92138342, 0.13055966, 0.83423144, 0.17328083])

In [36]:
mask = random_array > 0.5 # 生成一个布尔数组
mask

array([ True,  True, False,  True,  True, False,  True, False,  True,
       False])

In [37]:
tang_array[mask] # 使用布尔数组作为下标

array([ 0, 10, 30, 40, 60, 80])

In [38]:
tang_array = np.array([10,20,30,40,50]) 
tang_array > 30

array([False, False, False,  True,  True])

In [39]:
np.where(tang_array > 30) # 返回满足条件的元素的下标

(array([3, 4], dtype=int64),)

In [40]:
tang_array[np.where(tang_array > 30)] # 返回满足条件的元素

array([40, 50])

In [41]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [42]:
tang_array.dtype # 查看数组的数据类型

dtype('float32')

In [43]:
tang_array.nbytes # 查看数组占用的字节数

20

In [44]:
tang_array = np.array([1, 10, 3.5, 4], dtype=np.float32)
tang_array

array([ 1. , 10. ,  3.5,  4. ], dtype=float32)

In [45]:
tang_array * 2

array([ 2., 20.,  7.,  8.], dtype=float32)

In [46]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [47]:
tang_array

array([1, 2, 3, 4, 5])

In [48]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)

In [49]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [50]:
tang_array

array([1, 2, 3, 4, 5])

In [51]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [52]:
tang_array 

array([1, 2, 3, 4, 5])