In [1]:
import numpy as np
tang_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [2]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [3]:
np.sort(tang_array,axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [4]:
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [5]:
np.argsort(tang_array)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [6]:
tang_array = np.linspace(0,10,10)
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
values = np.array([2.5,6.5,9.5])

In [8]:
np.searchsorted(tang_array,values) 

array([3, 6, 9], dtype=int64)

In [12]:
tang_array = np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [15]:
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]]) # lexsort()函数返回的是排序后的索引
index
# np.lexsort 是 NumPy 中的一个函数，用于对多个键进行字典序排序（lexicographical sort）。
# 它返回一个索引数组，该数组可以用于对原始数组进行排序，使其按指定的键顺序排列。

array([0, 1, 2, 3], dtype=int64)

In [16]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])