### 数组形状操作

In [1]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
tang_array.shape

(2, 5)

In [7]:
tang_array.shape = (2,5)

In [8]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变

In [10]:
# tang_array .shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [25]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [26]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 10)

In [27]:
tang_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [29]:
tang_array = tang_array[:,np.newaxis]
tang_array.shape

(10, 1)

In [30]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [31]:
tang_array = tang_array.squeeze() # 去掉多余的维度
tang_array.shape

(10,)

In [32]:
tang_array.shape = 2,5

In [33]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
tang_array.transpose() # 转置

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [36]:
tang_array.T # 转置

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [37]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [38]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [39]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [40]:
c = np.concatenate((a,b)) # 拼接
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [41]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [42]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [43]:
c.shape

(2, 6)

In [44]:
np.vstack((a,b)) # 垂直拼接

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [45]:
np.hstack((a,b)) # 水平拼接

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [46]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [47]:
a.flatten() # 展平 降维 一维数组

array([ 123,  456,  678, 3214,  456,  134])

In [48]:
a


array([[ 123,  456,  678],
       [3214,  456,  134]])

In [49]:
a.ravel() # 展平 降维 一维数组 # 与flatten()的区别在于返回拷贝还是返回视图 

# a.flatten() 返回数组的一个副本（copy），对返回的数组进行修改不会影响原数组。
# a.ravel() 返回数组的一个视图（view），如果可能的话，对返回的数组进行修改会影响原数组。

array([ 123,  456,  678, 3214,  456,  134])

array([[ 123,  456,  678],
       [3214,  456,  134]])