# 数组生成

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

构造出来一个数组

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [6]:
np.linspace(0,10,10) # linespace 是等差数列，第一个参数是起始值，第二个参数是终止值，第三个参数是元素个数

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

默认是10为底的

In [7]:
print(help(np.logspace))

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boo

In [8]:
np.logspace(0,1,5) # logspace 是等比数列，第一个参数是起始值，第二个参数是终止值，第三个参数是元素个数

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [19]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [20]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [21]:
x, y= np.meshgrid(x,y) # meshgrid 生成网格点坐标矩阵 # x 是行向量，y 是列向量

In [22]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [24]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [25]:
np.r_[0:10:1] # r_ 是快速生成数组的方法

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.c_[0:10:1] # c_ 是快速生成数组的方法

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

更常用的 zeros ones

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [31]:
np.ones((3,3),dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
a = np.empty(6)
a.shape

(6,)

In [36]:
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

In [37]:
tang_array = np.array([1,2,3,4])
tang_array

array([1, 2, 3, 4])

In [38]:
np.zeros_like(tang_array) # zeros_like 生成和输入数组形状一样的全零数组

array([0, 0, 0, 0])

In [39]:
np.ones_like(tang_array) # ones_like 生成和输入数组形状一样的全一数组

array([1, 1, 1, 1])

In [40]:
np.identity(5) # identity 生成单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])