In [1]:
import numpy as np

In [2]:
x = np.array([5,5])
y = np.array([2,2])

In [3]:
np.multiply(x,y) # 矩阵对应元素相乘

array([10, 10])

In [4]:
np.dot(x,y) # 矩阵点乘

20

In [5]:
x.shape

(2,)

In [6]:
y.shape

(2,)

In [7]:
x.shape = 2,1

In [8]:
x

array([[5],
       [5]])

In [9]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
y.shape = 1,2
y

array([[2, 2]])

In [13]:
x

array([[5],
       [5]])

In [14]:
print (x.shape)
print (y.shape)

(2, 1)
(1, 2)


In [12]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [15]:
np.dot(y,x)

array([[20]])

In [18]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])

print (f'x hape:{x.shape}')
print (f'y shape:{y.shape}')

print (x * y)
print(f'\n{np.multiply(x,y)}')
print(f'\n{np.dot(y,x)}')

x hape:(3,)
y shape:(2, 3)
[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[ 6 15]


In [20]:
y = np.array([1,1,1,4])
x = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

In [21]:
np.logical_and(x,y) # 逻辑与 两个都为真才为真

array([ True,  True,  True,  True])

In [22]:
np.logical_or(x,y) # 逻辑或 两个都为假才为假

array([ True,  True,  True,  True])

In [23]:
np.logical_not(x,y) # 逻辑非 两个都为真才为假

array([0, 0, 0, 0])