### Numpy的随机模块

In [1]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.34062263, 0.58189391],
       [0.76222268, 0.9154902 ],
       [0.26433138, 0.46602193]])

In [5]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4)) # 10以内的随机整数 randint( low, high=None, size=None, dtype='l')

array([[7, 6, 6, 9],
       [7, 3, 2, 6],
       [5, 1, 9, 1],
       [3, 3, 8, 8],
       [4, 9, 5, 4]])

In [6]:
np.random.rand() #返回一个随机的浮点数

0.3733739188871117

In [9]:
np.random.random_sample()

0.29279157989640825

In [11]:
np.random.randint(0,10,3) #返回一个随机的整数

array([8, 4, 8])

In [12]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10) # 生成一个正态分布的随机数 # normal(loc=0.0, scale=1.0, size=None)

array([-0.01612773, -0.07842512,  0.0203844 ,  0.09084598, -0.16582271,
        0.12697273,  0.07067764, -0.03183309, -0.01969053, -0.05139634])

In [15]:
np.set_printoptions(precision = 3) # 设置打印的精度 # precision=None, suppress=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, **kwarg

In [16]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.064, -0.009,  0.103, -0.02 ,  0.198, -0.154, -0.093, -0.067,
        0.066,  0.014])

### 洗牌

In [17]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.random.shuffle(tang_array) # 打乱数组的顺序

In [19]:
tang_array

array([1, 7, 6, 4, 5, 8, 9, 0, 3, 2])

### 随机的种子

In [33]:
np.random.seed(100) # 设置随机种子

In [34]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.175,  0.034,  0.115, -0.025,  0.098,  0.051,  0.022, -0.107,
       -0.019,  0.026])