## Numpy练习题

打印当前Numpy版本

In [2]:
import numpy as np

In [2]:
print (np.__version__)

1.26.4


构造一个全零的矩阵，并打印其占用的内存大小

In [3]:
z = np.zeros((5,5))
print ('%d bytes'%(z.size * z.itemsize))

200 bytes


打印一个函数的帮助文档，比如numpy.add

In [4]:
print (help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

创建一个10-49的数组，并将其倒序排列

In [5]:
chen_array = np.arange(10, 50, 1)
chen_array = chen_array[::-1]

# chen_array = sorted(chen_array, reverse=True)
# chen_array = np.array(chen_array).transpose()
chen_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组中不为0的索引

In [6]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10], dtype=int64),)

随机构造一个3*3矩阵，并打印其中最大与最小值

In [7]:
tang_array = np.random.random((3,3))
print(tang_array.min())
print(tang_array.max())

0.016399308272833757
0.8341440094173924


构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [8]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array,pad_width = 2,mode = 'constant',constant_values = 0) # pad_width = 2, mode = 'constant', constant_values = 0 
# pad(array, pad_width, mode='constant', **kwargs)
tang_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
print (help(np.pad))

Help on _ArrayFunctionDispatcher in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.

    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
        for each axis.
        ``(before, after)`` or ``((before, after),)`` yields same before
        and after pad for each axis.
        ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
        for all axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.

        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
      

构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [33]:
np.unravel_index(100,(6,7,8)) # unravel_index(indices, dims, order='C') 是一个将一维索引转换为多维索引的函数
# (1, 5, 6) 1*8*7 + 5*8 + 6 = 100

(1, 5, 4)

对一个5*5的矩阵做归一化操作

In [4]:
tang_array = np.random.random((5,5))
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array-tang_min)/(tang_max - tang_min)
tang_array

array([[0.29969785, 0.44377563, 0.40516349, 0.30498287, 0.57880775],
       [0.65647566, 0.41045194, 0.52789852, 0.652672  , 0.25228634],
       [0.42580205, 0.63318628, 0.68878971, 0.29257236, 0.13064536],
       [0.5668303 , 1.        , 0.34741552, 0.79471579, 0.        ],
       [0.43927303, 0.80963084, 0.10697986, 0.96026196, 0.9199032 ]])

找到两个数组中相同的值

In [5]:
z1 = np.random.randint(0,10,10) 
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))

[1 1 9 7 6 4 8 2 4 7]
[5 0 8 0 4 8 3 2 1 2]
[1 2 4 8]


得到今天 明天 昨天的日期

In [6]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [7]:
yesterday

numpy.datetime64('2024-10-21')

In [8]:
today

numpy.datetime64('2024-10-22')

In [11]:
tommorow

numpy.datetime64('2024-10-23')

得到一个月中所有的天

In [12]:
np.arange('2017-10','2017-11',dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

得到一个数的整数部分


In [13]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([4., 0., 1., 0., 5., 0., 2., 7., 3., 1.])

构造一个数组，让它不能被改变

In [14]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

打印大数据的部分值，全部值

In [15]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

找到在一个数组中，最接近一个数的索引

In [24]:
z = np.arange(100)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(z-v)).argmin()
print (index)
print (z[index])

85.21693448205562
85
85


32位float类型和32位int类型转换

In [17]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print (z.dtype)

int32
float32


打印数组元素位置坐标与数值

In [29]:
z = np.arange(9).reshape(3,3)
print (z)
print ('\n')
for index,value in np.ndenumerate(z):
    print (index,value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


按照数组的某一列进行排序

In [63]:
z = np.random.randint(0,10,(3,3))
print (z)
print ('\n')
print (z[z[:,1].argsort()]) # 按照第二列排序

[[3 5 9]
 [8 4 1]
 [7 7 7]]


[[8 4 1]
 [3 5 9]
 [7 7 7]]


统计数组中每个数值出现的次数

In [64]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, ..., 0, 0, 1], dtype=int64)

如何对一个四维数组的最后两维来求和

In [66]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[79, 97, 87, 67],
       [49, 85, 81, 64],
       [68, 92, 57, 75],
       [49, 66, 65, 74]])

交换矩阵中的两行

In [68]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]] 
z


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
# 创建一个包含 25 个元素的数组，并将其重塑为 5x5 的二维数组
z = np.arange(25).reshape(5, 5)
print("原始数组：")
print(z)

# 交换第0列和第1列
z[:, [0, 1]] = z[:, [1, 0]]
print("交换第0列和第1列后的数组：")
print(z)

原始数组：
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
交换第0列和第1列后的数组：
[[ 1  0  2  3  4]
 [ 6  5  7  8  9]
 [11 10 12 13 14]
 [16 15 17 18 19]
 [21 20 22 23 24]]


找到一个数组中最常出现的数字

In [70]:
z = np.random.randint(0,10,50)
print (np.bincount(z).argmax())

4


快速查找TOP K

In [73]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argpartition(-z,n)[:n]]) # argpartition 返回的是索引 从大到小排序 取前n个 最小的n个 从小到大排序

[9997 9998 9999 9996 9995]


去除掉一个数组中，所有元素都相同的数据

In [103]:
import numpy as np
import sys

# 设置打印选项，threshold 为 sys.maxsize 可以显示整个数组
np.set_printoptions(threshold=sys.maxsize)

# 生成一个包含 0, 1, 2 的随机数组
z = np.random.randint(0, 3, (10, 3))
print(z)

# 过滤掉所有行内元素相同的数据
filtered_z = z[~np.all(z[:, 1:] == z[:, :-1], axis=1)]
print(filtered_z)

[[0 2 1]
 [0 1 1]
 [0 2 1]
 [2 2 0]
 [1 2 0]
 [1 2 2]
 [1 1 1]
 [0 2 0]
 [0 0 0]
 [2 1 2]]
[[0 2 1]
 [0 1 1]
 [0 2 1]
 [2 2 0]
 [1 2 0]
 [1 2 2]
 [0 2 0]
 [2 1 2]]


In [104]:
e = np.all(z[:,1:] == z[:,:-1], axis=1)
print (e)

[False False False False False False  True False  True False]


In [105]:
z = np.random.randint(0, 3, (10, 3))
print("Original array:")
print(z)

# Remove rows where all elements are the same
z = z[~np.all(z[:, 1:] == z[:, :-1], axis=1)]
print("Array after removing rows with all elements the same:")
print(z)

Original array:
[[2 1 2]
 [1 2 1]
 [2 0 2]
 [2 0 2]
 [0 0 1]
 [1 1 2]
 [2 1 0]
 [0 2 1]
 [1 0 1]
 [2 1 0]]
Array after removing rows with all elements the same:
[[2 1 2]
 [1 2 1]
 [2 0 2]
 [2 0 2]
 [0 0 1]
 [1 1 2]
 [2 1 0]
 [0 2 1]
 [1 0 1]
 [2 1 0]]


In [106]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a == b)

False

In [108]:
np.any(a == b)

True